spring:
 datasource:
  url: jdbc:h2:mem:device;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
  username: sa
  password:
  driverClassName: org.h2.Driver
  schema: classpath:/sql/schema.sql
  data: classpath:/sql/data.sql
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: none