spring:
 datasource:
  driverClassName: org.postgresql.Driver
  max-active: 1
  min-idle: 1
  initial-size: 1
  removeAbandoned: true
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    temp:
     use_jdbc_metadata_defaults: false
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
   ddl-auto: none

server:
  port: ${PORT:8080}
